print('________________________________')
print('          Hello World')
print('________________________________')
name = input('Please enter your name: ')
print('......................')
print(name)
print('......................')